### ISSUE TITLE
Isuue With Bot on my Discord Server

### ISSUE THREAD

**Issue by jpal3** [ChillFish8/Crunchy#2]
The 2nd page of all the lists are broken. This includes the characters list, the favorite anime list, watched anime list.

![Screenshot 2020-09-14 161534](https://user-images.githubusercontent.com/42350580/93133644-8f27ac00-f6a5-11ea-9970-c963586533de.png)
![Screenshot 2020-09-14 161514](https://user-images.githubusercontent.com/42350580/93133645-8f27ac00-f6a5-11ea-9ff3-95e3fc1e35a4.png)
![Screenshot 2020-09-14 161210](https://user-images.githubusercontent.com/42350580/93133646-8f27ac00-f6a5-11ea-9e5a-f022dc2c9fde.png)
![Screenshot 2020-09-14 161144](https://user-images.githubusercontent.com/42350580/93133647-8f27ac00-f6a5-11ea-98ee-5afce9645c26.png)

**Comment by ChillFish8** [comment]
Yikes, Ty for making this issue. I'll try roll out a fix for it by this weekend

**Comment by ChillFish8** [comment]
[The latest commit](https://github.com/ChillFish8/Crunchy/commit/72c87ad5dc0a4aa374ab0dad3ad80842a15a560a) should have fixed this for all systems now, the update will roll out in a few minutes.
